name: Generate search index

on:
  # Enable running on demand
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # This job will
  # - Download the latest spreadsheet
  # - Look for cache of previous cargo release build and run release build to generate json
  search_index:
    name: Generate search index
    runs-on: ubuntu-latest
    steps:
      - name: Install binary
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/Rigellute/lute-spreadsheet-to-meilisearch/releases/download/v0.1.0/rust-excel-to-meilisearch-installer.sh | sh

      - name: Verify installation
        run: |
          which rust-excel-to-meilisearch || echo "Binary not found in PATH"

      - name: Run binary
        run: |
          rust-excel-to-meilisearch
        env:
          MEILISEARCH_API_KEY: ${{ secrets.MEILI_API_KEY }}
          MEILISEARCH_HOST: https://lute-search.rigellute.com
          LUTE_MUSIC_URL: https://browse.lutemusic.org/spreadsheet.xlsx
